import Header from '@/components/Header/Header';
import './globals.css';
import { Outfit, Roboto_Slab, Roboto_Serif, Poppins } from 'next/font/google';
import MobileMenu from '@/components/Header/MobileHeader';

const outfit = Outfit({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-outfit',
});
const roboto_slap = Roboto_Slab({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto_slap',
});
const roboto_serif = Roboto_Serif({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto_serif',
});
const poppins = Poppins({
  subsets: [],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['800', '500', '700', '400'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={` ${poppins.variable} ${roboto_serif.variable} ${outfit.variable}  ${roboto_slap.variable}`}
    >
      <body>
        <Header />
        <MobileMenu />
        <main className=" pt-[100px]"> {children}</main>
      </body>
    </html>
  );
}
